name: Cypress Tests

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_baseUrl: ${{ vars.DEV_ENV_URL }}
      # CYPRESS_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      # CYPRESS_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Cache npm dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v7
        with:
          browser: electron
          headed: false
      # Upload screenshots as artifacts if test fails
      - name: Upload Cypress artifacts (screenshots)
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: cypress-media
          path: cypress/screenshots